server:
  port: 8082 # Puerto para este servicio

spring:
  application:
    name: usuario-equipo-service
  datasource:
    url: jdbc:mysql://localhost:3306/equipos_db # Apunta a tu nueva BD
    username: root
    password: sergioc
  jpa:
    hibernate:
      ddl-auto: update # Sincroniza las tablas con tus entidades
    show-sql: true