server:
  port: 8085 # Puerto Ãºnico para este servicio

spring:
  application:
    name: notificaciones-service
  datasource:
    url: jdbc:mysql://localhost:3306/notificaciones_db # Apunta a la BD de notificaciones
    username: root
    password: sergioc
  jpa:
    hibernate:
      ddl-auto: update # Sincroniza las tablas con tus entidades
    show-sql: true